# permissions for end users to view chronoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chrono-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chrono
    app.kubernetes.io/part-of: chrono
    app.kubernetes.io/managed-by: kustomize
  name: chrono-viewer-role
rules:
- apiGroups:
  - chrono.chrono.local
  resources:
  - chronoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chrono.chrono.local
  resources:
  - chronoes/status
  verbs:
  - get
