---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - chrono.chrono.local
  resources:
  - chronoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chrono.chrono.local
  resources:
  - chronoes/finalizers
  verbs:
  - update
- apiGroups:
  - chrono.chrono.local
  resources:
  - chronoes/status
  verbs:
  - get
  - patch
  - update
